# Generated by Django 4.1.7 on 2023-04-26 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestPlace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GestPlace.place'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GestPlace.category'),
        ),
    ]
