# Generated by Django 4.1.7 on 2023-04-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestPlace', '0003_alter_localisation_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='specifity',
        ),
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
